//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblog.ASP.NET.Webform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogComment
    {
        public int NewsComment { get; set; }
        public int NewsID { get; set; }
        public string FullName { get; set; }
        public string webSite { get; set; }
        public string Email { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsActive { get; set; }
        public string NewsCommentText { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
